/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUIController.VeranstaltungsSuchenCtrl;
import java.util.List;
import java.util.LinkedList;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableModel;
/**
 *
 * @author Monika Hallo Monika
 */
public class VeranstaltungSuchen extends javax.swing.JFrame {
    private VeranstaltungsSuchenCtrl ctrl;
    //private List<Object[]> veranstInfoList = new LinkedList<>();
    
    
    /**
     * Creates new form VeranstaltungSuchen
     */
    public VeranstaltungSuchen(VeranstaltungsSuchenCtrl controller) {       
        initComponents();
        this.setVisible(true);
        ctrl = controller;
        //loadComponents();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelScreen = new javax.swing.JPanel();
        jPanelScreenTitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelEventSearch = new javax.swing.JPanel();
        jPanelSearchLabels = new javax.swing.JPanel();
        jLabelDate = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelArtist = new javax.swing.JLabel();
        jPanelSearchButton = new javax.swing.JPanel();
        jPanelSearchInput = new javax.swing.JPanel();
        jTextFieldDate = new javax.swing.JTextField();
        jTextFieldPlace = new javax.swing.JTextField();
        jTextFieldArtist = new javax.swing.JTextField();
        jPanelDeleteSearchButton = new javax.swing.JPanel();
        jButtonSearchStart = new javax.swing.JButton();
        jPanelSearchDelete = new javax.swing.JPanel();
        jButtonSearchDelete = new javax.swing.JButton();
        jPanelEventTable = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVeranstaltungen = new javax.swing.JTable();
        jPanelInfoBack = new javax.swing.JPanel();
        jPaneInfo = new javax.swing.JPanel();
        jPanelBackButton = new javax.swing.JPanel();
        jButtonBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 1));

        jPanelScreen.setLayout(new java.awt.GridLayout(4, 1));

        jPanelScreenTitle.setLayout(new java.awt.GridLayout(1, 1));

        jLabel1.setText("Veranstaltung suchen");
        jPanelScreenTitle.add(jLabel1);

        jPanelScreen.add(jPanelScreenTitle);

        jPanelEventSearch.setLayout(new java.awt.GridLayout(2, 4));

        jPanelSearchLabels.setLayout(new java.awt.GridLayout(1, 1));

        jLabelDate.setText("Datum");
        jPanelSearchLabels.add(jLabelDate);

        jLabelName.setText("Veranstaltungsort");
        jPanelSearchLabels.add(jLabelName);

        jLabelArtist.setText("Künstler");
        jPanelSearchLabels.add(jLabelArtist);

        jPanelSearchButton.setLayout(new java.awt.GridLayout(1, 1));
        jPanelSearchLabels.add(jPanelSearchButton);

        jPanelEventSearch.add(jPanelSearchLabels);

        jPanelSearchInput.setLayout(new java.awt.GridLayout(1, 5));

        jTextFieldDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDateActionPerformed(evt);
            }
        });
        jPanelSearchInput.add(jTextFieldDate);

        jTextFieldPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPlaceActionPerformed(evt);
            }
        });
        jPanelSearchInput.add(jTextFieldPlace);

        jTextFieldArtist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldArtistActionPerformed(evt);
            }
        });
        jPanelSearchInput.add(jTextFieldArtist);

        jPanelDeleteSearchButton.setLayout(new java.awt.GridLayout(1, 1));

        jButtonSearchStart.setText("Suchen");
        jButtonSearchStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchStartActionPerformed(evt);
            }
        });
        jPanelDeleteSearchButton.add(jButtonSearchStart);

        jPanelSearchInput.add(jPanelDeleteSearchButton);

        jPanelSearchDelete.setLayout(new java.awt.GridLayout(1, 0));

        jButtonSearchDelete.setText("Eingabe löschen");
        jButtonSearchDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchDeleteActionPerformed(evt);
            }
        });
        jPanelSearchDelete.add(jButtonSearchDelete);

        jPanelSearchInput.add(jPanelSearchDelete);

        jPanelEventSearch.add(jPanelSearchInput);

        jPanelScreen.add(jPanelEventSearch);

        jPanelEventTable.setLayout(new java.awt.GridLayout(1, 1));

        jTableVeranstaltungen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Datum", "Name", "Ort", "Künstler", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableVeranstaltungen.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTableVeranstaltungen);
        jTableVeranstaltungen.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jPanelEventTable.add(jScrollPane1);

        jPanelScreen.add(jPanelEventTable);

        jPanelInfoBack.setLayout(new java.awt.GridLayout(1, 2));

        jPaneInfo.setLayout(new java.awt.GridLayout(1, 2));
        jPanelInfoBack.add(jPaneInfo);

        jButtonBack.setText("Cancel");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBackButtonLayout = new javax.swing.GroupLayout(jPanelBackButton);
        jPanelBackButton.setLayout(jPanelBackButtonLayout);
        jPanelBackButtonLayout.setHorizontalGroup(
            jPanelBackButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
            .addGroup(jPanelBackButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBackButtonLayout.createSequentialGroup()
                    .addGap(0, 77, Short.MAX_VALUE)
                    .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 77, Short.MAX_VALUE)))
        );
        jPanelBackButtonLayout.setVerticalGroup(
            jPanelBackButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 136, Short.MAX_VALUE)
            .addGroup(jPanelBackButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelBackButtonLayout.createSequentialGroup()
                    .addGap(0, 11, Short.MAX_VALUE)
                    .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 11, Short.MAX_VALUE)))
        );

        jPanelInfoBack.add(jPanelBackButton);

        jPanelScreen.add(jPanelInfoBack);

        getContentPane().add(jPanelScreen);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSearchDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchDeleteActionPerformed
        btnSearchDeleteClicked();
    }//GEN-LAST:event_jButtonSearchDeleteActionPerformed

    private void jTextFieldDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDateActionPerformed

    private void jButtonSearchStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchStartActionPerformed
        btnSearchStartClicked();
    }//GEN-LAST:event_jButtonSearchStartActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        btnBackClicked();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jTextFieldPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPlaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlaceActionPerformed

    private void jTextFieldArtistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldArtistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldArtistActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonSearchDelete;
    private javax.swing.JButton jButtonSearchStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelArtist;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JPanel jPaneInfo;
    private javax.swing.JPanel jPanelBackButton;
    private javax.swing.JPanel jPanelDeleteSearchButton;
    private javax.swing.JPanel jPanelEventSearch;
    private javax.swing.JPanel jPanelEventTable;
    private javax.swing.JPanel jPanelInfoBack;
    private javax.swing.JPanel jPanelScreen;
    private javax.swing.JPanel jPanelScreenTitle;
    private javax.swing.JPanel jPanelSearchButton;
    private javax.swing.JPanel jPanelSearchDelete;
    private javax.swing.JPanel jPanelSearchInput;
    private javax.swing.JPanel jPanelSearchLabels;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVeranstaltungen;
    private javax.swing.JTextField jTextFieldArtist;
    private javax.swing.JTextField jTextFieldDate;
    private javax.swing.JTextField jTextFieldPlace;
    // End of variables declaration//GEN-END:variables

    public void btnSearchStartClicked() {
        String date = jTextFieldDate.getText();
        String place = jTextFieldPlace.getText();
        String artist = jTextFieldArtist.getText();
        ctrl.searchingForEvents(date, place, artist);
    }
    
    private void btnSearchDeleteClicked() {
        ctrl.deleteSearchInputs();
    }
    private void btnBackClicked() {
        ctrl.deleteVeranstaltungInfo();
    }
    
    private void setTableModel() {
       jTableVeranstaltungen.setModel(ctrl.getVeramstaltungInfoModel());
       jTableVeranstaltungen.getModel().addTableModelListener(new TableModelListener() {
           @Override
           public void tableChanged(TableModelEvent e) {
               int row = e.getFirstRow();
               int column = e.getColumn();
               TableModel model = (TableModel) e.getSource();
               Object[] changedRow = new Object[model.getColumnCount()];
               for (int i = 0; i < changedRow.length; i++) {
                   changedRow[i] = model.getValueAt(row, i);
               }               
           }         
       });
    }
    
    private void veranstaltungAuswaehlen() {
        
    }
    
}
